version: 0.8
wild:
  build: false
  break: true
  opOverride: true
outposts:
  enabled: true
  maxSizeEnabled: true
  maxCount: 99
  maxX: 400
  maxZ: 400
  monsterFlag: false
  animalFlag: false
  blockFlag: true
  fireFlag: true
  bombFlag: true
  pvpFlag: true
town:
  maxSizeEnabled: false
  maxX: 1000
  maxZ: 1000
  monsterFlag: true
  animalFlag: true
  blockFlag: true
  fireFlag: true
  bombFlag: true
  pvpFlag: true
sanctuary:
  opBuild: true
  playerBuild: false
default-flags:
  monsters:
    blaze: true
    cave_spider: true
    creeper: true
    ender_dragon: true
    enderman: true
    ghast: true
    giant: true
    magma_cube: true
    pig_zombie: true
    silverfish: true
    skeleton: true
    slime: true
    spider: true
    squid: true
    zombie: true
  animals:
    chicken: false
    cow: false
    irongolem: true
    mooshroom: false
    pig: false
    sheep: false
    snowman: true
    villager: true
    wolf: false
  blocks:
    simple-default: 10,11,51
    final: 46,52
    unblockable: 0,26,90
  fire:
    burn: true
  explode:
    blocked: true
  pvp:
    blocked: true
world:
database:
  type: yml
  prefix: SZ_
  mysql:
    host: localhost
    port: 3306
    database: simplezones
    username: simplezones
    password: simplezones