version: 0.5
wild:
  build: false
  break: true
default-flags:
  monsters:
    blaze: true
    cave_spider: true
    creeper: true
    ender_dragon: true
    enderman: true
    ghast: true
    giant: true
    magma_cube: true
    pig_zombie: true
    silverfish: true
    skeleton: true
    slime: true
    spider: true
    squid: true
    zombie: true
  animals:
    chicken: false
    cow: false
    irongolem: true
    mooshroom: false
    pig: false
    sheep: false
    snowman: true
    villager: true
    wolf: false
  blocks:
    simple-default: 10,11,51
    final: 46,52
    unblockable: 0,26,90
  fire:
    burn: true
  explode:
    blocked: true
database:
  type: yml
  prefix: SZ_
  mysql:
    host: localhost
    port: 3306
    database: simplezones
    username: simplezones
    password: simplezones